_BASE_: [
  '../datasets/coco_detection_my.yml',
  '../runtime.yml',
  '_base_/optimizer_120e.yml',
  '_base_/ssd_mobilenet_v1_300.yml',
  '_base_/ssd_mobilenet_reader.yml',
]
weights: output/ssd_mobilenet_v1_300_120e_custom_reduced_classes/model_final
save_dir: output/ssd_mobilenet_v1_300_120e_custom_reduced_classes
output_eval: evaluations/ssd_mobilenet_v1_300_120e_custom_reduced_classes

snapshot_epoch: 10

  # set collate_batch to false because ground-truth info is needed
# on voc dataset and should not collate data in batch when batch size
# is larger than 1.
#EvalReader:
#  collate_batch: false

wandb:
  project: picodet
  entity: ltophoen
