metric: COCO
num_classes: 4

TrainDataset:
  !COCODataSet
    image_dir: images/train
    anno_path: annotations/instances_train.json
    dataset_dir: ../Auto_PoD_training/data
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: images/val
    anno_path: annotations/instances_val.json
    dataset_dir: ../Auto_PoD_training/data

TestDataset:
  !ImageFolder
    image_dir: images/test
    anno_path: annotations/instances_test.json # also support txt (like VOC's label_list.txt)
    dataset_dir: ../Auto_PoD_training/data # if set, anno_path will be 'dataset_dir/anno_path'
